# frozen_string_literal: true

require "spec_helper"
require_relative "../fixtures/sample_jobs"

RSpec.describe ActiveJob::Temporal::WorkflowIdBuilder do
  subject(:builder) { described_class.new }

  describe "#build" do
    let(:job) do
      job = SimpleJob.new
      job.job_id = "abc-123"
      job
    end

    it "returns the default workflow ID format" do
      expect(builder.build(job)).to eq("ajwf:SimpleJob:abc-123")
    end

    it "is deterministic for the same job instance" do
      expect(builder.build(job)).to eq(builder.build(job))
    end

    it "includes the job class name" do
      scheduled_job = ScheduledJob.new
      scheduled_job.job_id = job.job_id

      expect(builder.build(scheduled_job)).to eq("ajwf:ScheduledJob:abc-123")
      expect(builder.build(scheduled_job)).not_to eq(builder.build(job))
    end

    it "includes the job ID" do
      other_job = SimpleJob.new
      other_job.job_id = "def-456"

      expect(builder.build(other_job)).to eq("ajwf:SimpleJob:def-456")
      expect(builder.build(other_job)).not_to eq(builder.build(job))
    end

    it "uses the injected strategy when provided" do
      custom_builder = described_class.new(->(job) { "custom:#{job.job_id}" })

      expect(custom_builder.build(job)).to eq("custom:abc-123")
    end

    it "prefers the job class workflow ID block over the injected strategy" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "ClassIdentityJob"

        temporal_workflow_id { |account_id| "account:#{account_id}" }
      end
      custom_builder = described_class.new(->(current_job) { "global:#{current_job.job_id}" })
      identity_job = job_class.new("acct-123")
      identity_job.job_id = "abc-123"

      expect(custom_builder.build(identity_job)).to eq("account:acct-123")
    end

    it "uses workflow ID blocks with perform arguments" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PaymentJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end
      identity_job = job_class.new("pay-123")
      identity_job.job_id = "abc-123"

      expect(builder.build(identity_job)).to eq("payment:pay-123")
    end

    it "uses workflow ID prefixes with the ActiveJob job ID" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PrefixedPaymentJob"

        temporal_workflow_id_prefix "payment"
      end
      identity_job = job_class.new
      identity_job.job_id = "abc-123"

      expect(builder.build(identity_job)).to eq("payment:abc-123")
    end

    it "keeps generated workflow IDs stable across Ruby class renames" do
      original_class = Class.new(ActiveJob::Base) do
        def self.name = "ChargePaymentJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end
      renamed_class = Class.new(ActiveJob::Base) do
        def self.name = "Payments::ChargeJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end

      original_job = original_class.new("pay-123")
      renamed_job = renamed_class.new("pay-123")
      original_job.job_id = "abc-123"
      renamed_job.job_id = "abc-123"

      expect(builder.build(original_job)).to eq("payment:pay-123")
      expect(builder.build(renamed_job)).to eq("payment:pay-123")
    end

    it "rejects invalid workflow IDs generated by job class blocks" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "InvalidIdentityJob"

        temporal_workflow_id { |_payment_id| "payment\nbad" }
      end
      identity_job = job_class.new("pay-123")

      expect { builder.build(identity_job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /control characters/)
    end

    it "allows tenant-style workflow IDs" do
      custom_builder = described_class.new(->(job) { "tenant-42:ajwf:#{job.class.name}:#{job.job_id}" })

      expect(custom_builder.build(job)).to eq("tenant-42:ajwf:SimpleJob:abc-123")
    end

    it "allows Temporal-compatible punctuation and Unicode workflow IDs" do
      custom_builder = described_class.new(
        ->(job) { "tenant/acme@example.com/ajwf:RésuméJob:#{job.job_id}" }
      )

      expect(custom_builder.build(job)).to eq("tenant/acme@example.com/ajwf:RésuméJob:abc-123")
    end

    it "rejects non-string strategy output" do
      custom_builder = described_class.new(->(_job) { 123 })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /must return a String/)
    end

    it "rejects generators that cannot accept the job argument" do
      custom_builder = described_class.new(-> { "custom-id" })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /must accept one positional ActiveJob argument/)
    end

    it "rejects blank workflow IDs" do
      custom_builder = described_class.new(->(_job) { "" })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /must not be blank/)
    end

    it "rejects workflow IDs with control characters" do
      custom_builder = described_class.new(->(_job) { "bad\nworkflow" })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /control characters/)
    end

    it "rejects workflow IDs that are not UTF-8 compatible" do
      custom_builder = described_class.new(->(_job) { "\xC3".b })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /valid UTF-8/)
    end

    it "rejects workflow IDs longer than 255 characters" do
      custom_builder = described_class.new(->(_job) { "a" * 256 })

      expect { custom_builder.build(job) }
        .to raise_error(ActiveJob::Temporal::ConfigurationError, /maximum length is 255/)
    end
  end

  describe "#build_from_job_class" do
    it "returns the same format without a job instance" do
      workflow_id = builder.build_from_job_class(SimpleJob, "550e8400-e29b-41d4-a716-446655440000")

      expect(workflow_id).to eq("ajwf:SimpleJob:550e8400-e29b-41d4-a716-446655440000")
    end

    it "uses workflow ID prefixes without a job instance" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PrefixedLookupJob"

        temporal_workflow_id_prefix "lookup"
      end

      workflow_id = builder.build_from_job_class(job_class, "550e8400-e29b-41d4-a716-446655440000")

      expect(workflow_id).to eq("lookup:550e8400-e29b-41d4-a716-446655440000")
    end
  end
end
