# frozen_string_literal: true

require "spec_helper"
require_relative "../fixtures/sample_jobs"

describe ActiveJob::Temporal::WorkflowIdBuilder do
  let(:builder) { described_class.new }

  describe "#build" do
    let(:job) do
      job = SimpleJob.new
      job.job_id = "abc-123"
      job
    end

    it "returns the default workflow ID format" do
      assert_equal "ajwf:SimpleJob:abc-123", builder.build(job)
    end

    it "is deterministic for the same job instance" do
      assert_equal builder.build(job), builder.build(job)
    end

    it "includes the job class name" do
      scheduled_job = ScheduledJob.new
      scheduled_job.job_id = job.job_id

      assert_equal "ajwf:ScheduledJob:abc-123", builder.build(scheduled_job)
      refute_equal builder.build(job), builder.build(scheduled_job)
    end

    it "includes the job ID" do
      other_job = SimpleJob.new
      other_job.job_id = "def-456"

      assert_equal "ajwf:SimpleJob:def-456", builder.build(other_job)
      refute_equal builder.build(job), builder.build(other_job)
    end

    it "uses the injected strategy when provided" do
      custom_builder = described_class.new(->(job) { "custom:#{job.job_id}" })

      assert_equal "custom:abc-123", custom_builder.build(job)
    end

    it "prefers the job class workflow ID block over the injected strategy" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "ClassIdentityJob"

        temporal_workflow_id { |account_id| "account:#{account_id}" }
      end
      custom_builder = described_class.new(->(current_job) { "global:#{current_job.job_id}" })
      identity_job = job_class.new("acct-123")
      identity_job.job_id = "abc-123"

      assert_equal "account:acct-123", custom_builder.build(identity_job)
    end

    it "uses workflow ID blocks with perform arguments" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PaymentJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end
      identity_job = job_class.new("pay-123")
      identity_job.job_id = "abc-123"

      assert_equal "payment:pay-123", builder.build(identity_job)
    end

    it "uses workflow ID prefixes with the ActiveJob job ID" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PrefixedPaymentJob"

        temporal_workflow_id_prefix "payment"
      end
      identity_job = job_class.new
      identity_job.job_id = "abc-123"

      assert_equal "payment:abc-123", builder.build(identity_job)
    end

    it "keeps generated workflow IDs stable across Ruby class renames" do
      original_class = Class.new(ActiveJob::Base) do
        def self.name = "ChargePaymentJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end
      renamed_class = Class.new(ActiveJob::Base) do
        def self.name = "Payments::ChargeJob"

        temporal_workflow_id { |payment_id| "payment:#{payment_id}" }
      end

      original_job = original_class.new("pay-123")
      renamed_job = renamed_class.new("pay-123")
      original_job.job_id = "abc-123"
      renamed_job.job_id = "abc-123"

      assert_equal "payment:pay-123", builder.build(original_job)
      assert_equal "payment:pay-123", builder.build(renamed_job)
    end

    it "rejects invalid workflow IDs generated by job class blocks" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "InvalidIdentityJob"

        temporal_workflow_id { |_payment_id| "payment\nbad" }
      end
      identity_job = job_class.new("pay-123")

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { builder.build(identity_job) }
      assert_match(/control characters/, error.message)
    end

    it "allows tenant-style workflow IDs" do
      custom_builder = described_class.new(->(job) { "tenant-42:ajwf:#{job.class.name}:#{job.job_id}" })

      assert_equal "tenant-42:ajwf:SimpleJob:abc-123", custom_builder.build(job)
    end

    it "allows Temporal-compatible punctuation and Unicode workflow IDs" do
      custom_builder = described_class.new(
        ->(job) { "tenant/acme@example.com/ajwf:RésuméJob:#{job.job_id}" }
      )

      assert_equal "tenant/acme@example.com/ajwf:RésuméJob:abc-123", custom_builder.build(job)
    end

    it "rejects non-string strategy output" do
      custom_builder = described_class.new(->(_job) { 123 })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/must return a String/, error.message)
    end

    it "rejects generators that cannot accept the job argument" do
      custom_builder = described_class.new(-> { "custom-id" })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/must accept one positional ActiveJob argument/, error.message)
    end

    it "rejects blank workflow IDs" do
      custom_builder = described_class.new(->(_job) { "" })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/must not be blank/, error.message)
    end

    it "rejects workflow IDs with control characters" do
      custom_builder = described_class.new(->(_job) { "bad\nworkflow" })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/control characters/, error.message)
    end

    it "rejects workflow IDs that are not UTF-8 compatible" do
      custom_builder = described_class.new(->(_job) { "\xC3".b })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/valid UTF-8/, error.message)
    end

    it "rejects workflow IDs longer than 255 characters" do
      custom_builder = described_class.new(->(_job) { "a" * 256 })

      error = assert_raises(ActiveJob::Temporal::ConfigurationError) { custom_builder.build(job) }
      assert_match(/maximum length is 255/, error.message)
    end
  end

  describe "#build_from_job_class" do
    it "returns the same format without a job instance" do
      workflow_id = builder.build_from_job_class(SimpleJob, "550e8400-e29b-41d4-a716-446655440000")

      assert_equal "ajwf:SimpleJob:550e8400-e29b-41d4-a716-446655440000", workflow_id
    end

    it "uses workflow ID prefixes without a job instance" do
      job_class = Class.new(ActiveJob::Base) do
        def self.name = "PrefixedLookupJob"

        temporal_workflow_id_prefix "lookup"
      end

      workflow_id = builder.build_from_job_class(job_class, "550e8400-e29b-41d4-a716-446655440000")

      assert_equal "lookup:550e8400-e29b-41d4-a716-446655440000", workflow_id
    end
  end
end
