usage: opensource
includes:
  - lib
  - spec
requires:
  - activejob/temporal
integration:
  name: minitest
matcher:
  subjects:
    - ActiveJob::Temporal::WorkflowIdBuilder#build
    - ActiveJob::Temporal::WorkflowIdBuilder.default_for
mutation:
  timeout: 5.0
