# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "rubocop/rake_task"
require "tempfile"
require "yard"

GENERATED_CHANGELOG_FOOTER = "\\* *This Changelog was automatically generated by " \
                             "[github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)*"
GENERATED_CHANGELOG_START = "<!-- github_changelog_generator:start -->"
GENERATED_CHANGELOG_END = "<!-- github_changelog_generator:end -->"
GENERATED_CHANGELOG_FOOTER_PATTERN = /\n\n#{Regexp.escape(GENERATED_CHANGELOG_FOOTER)}\n?\z/
GENERATED_UNRELEASED_HEADING_PATTERN = Regexp.new(
  "\\A## \\[Unreleased\\]\\([^)]+\\) \\(\\d{4}-\\d{2}-\\d{2}\\)\n\n" \
  "\\[Full Changelog\\]\\([^)]+\\)\n\n"
)
UNRELEASED_CHANGELOG_HEADING = /^## \[Unreleased\].*$/
RELEASED_CHANGELOG_HEADING = /^## \[(?:v?\d)/
CHANGELOG_INTRO = <<~MARKDOWN.chomp
  # Changelog

  All notable changes to this project will be documented in this file.

  The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
  and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
MARKDOWN

def generated_release_notes_from(changelog)
  generated_notes = changelog
                    .sub(/\A# Changelog\n+/, "")
                    .sub(GENERATED_CHANGELOG_FOOTER_PATTERN, "")
                    .sub(GENERATED_UNRELEASED_HEADING_PATTERN, "## [Unreleased]\n\n")
                    .rstrip

  generated_notes.sub(/\A## \[Unreleased\]\n\n/, "## [Unreleased]\n\n#{GENERATED_CHANGELOG_START}\n\n")
                 .concat("\n\n#{GENERATED_CHANGELOG_END}")
end

def manual_unreleased_notes_from(changelog)
  if changelog.include?(GENERATED_CHANGELOG_END)
    manual_notes_after_generated_section(changelog)
  else
    manual_notes_from_unmarked_unreleased_section(changelog)
  end
end

def manual_notes_after_generated_section(changelog)
  notes = changelog.split(GENERATED_CHANGELOG_END, 2).last.to_s
  released_heading_index = notes.index(RELEASED_CHANGELOG_HEADING)

  notes = notes[...released_heading_index] if released_heading_index
  notes.sub(GENERATED_CHANGELOG_FOOTER_PATTERN, "").strip
end

def manual_notes_from_unmarked_unreleased_section(changelog)
  unreleased_heading_index = changelog.index(UNRELEASED_CHANGELOG_HEADING)

  return "" unless unreleased_heading_index

  notes = changelog[unreleased_heading_index..].lines.drop(1).join
  released_heading_index = notes.index(RELEASED_CHANGELOG_HEADING)

  notes = notes[...released_heading_index] if released_heading_index
  notes.sub(GENERATED_CHANGELOG_FOOTER_PATTERN, "").strip
end

def released_history_from(changelog)
  released_heading_index = changelog.index(RELEASED_CHANGELOG_HEADING)

  return "" unless released_heading_index

  changelog[released_heading_index..]
    .sub(GENERATED_CHANGELOG_FOOTER_PATTERN, "")
    .rstrip
end

def merged_changelog(generated_changelog, existing_changelog)
  [
    CHANGELOG_INTRO,
    generated_release_notes_from(generated_changelog),
    manual_unreleased_notes_from(existing_changelog),
    released_history_from(existing_changelog),
    GENERATED_CHANGELOG_FOOTER
  ].reject(&:empty?).join("\n\n").concat("\n")
end

desc "Run the spec suite"
task spec: %i[spec:unit spec:integration spec:contract]

namespace :spec do
  desc "Run unit specs"
  RSpec::Core::RakeTask.new(:unit) do |t|
    t.pattern = "spec/unit/**/*_spec.rb"
    ENV["TEST_SUITE"] = "unit"
  end

  desc "Run integration specs"
  RSpec::Core::RakeTask.new(:integration) do |t|
    t.pattern = "spec/integration/**/*_spec.rb"
    ENV["TEST_SUITE"] = "integration"
  end

  desc "Run Temporal SDK contract specs"
  RSpec::Core::RakeTask.new(:contract) do |t|
    t.pattern = "spec/contract/**/*_spec.rb"
    ENV["TEST_SUITE"] = "contract"
  end

  desc "Run chaos specs"
  RSpec::Core::RakeTask.new(:chaos) do |t|
    t.pattern = "spec/chaos/**/*_spec.rb"
    ENV["TEST_SUITE"] = "chaos"
  end
end

RuboCop::RakeTask.new(:rubocop)

YARD::Rake::YardocTask.new(:yard)

desc "Run performance benchmarks"
task :benchmark do
  ruby "spec/benchmarks/activejob_temporal_benchmark.rb"
end

desc "Run the scoped mutation test suite"
task :mutation do
  sh "bundle", "exec", "mutant", "run"
end

namespace :changelog do
  desc "Generate CHANGELOG.md from GitHub issues and pull requests"
  task :generate do
    github_token = ENV["CHANGELOG_GITHUB_TOKEN"] || ENV.fetch("GITHUB_TOKEN", nil)

    abort "Set CHANGELOG_GITHUB_TOKEN or GITHUB_TOKEN to generate CHANGELOG.md" unless github_token

    Tempfile.create(["activejob-temporal-changelog", ".md"]) do |generated_changelog|
      generated_changelog.close

      sh({ "CHANGELOG_GITHUB_TOKEN" => github_token },
         "bundle",
         "exec",
         "github_changelog_generator",
         "--config-file",
         ".github_changelog_generator",
         "--output",
         generated_changelog.path,
         verbose: false)

      File.write("CHANGELOG.md", merged_changelog(File.read(generated_changelog.path), File.read("CHANGELOG.md")))
    end
  end
end

desc "Default: run rubocop and specs"
task default: %i[rubocop spec]
