config_version = "0"

exclude_patterns = [
  "coverage/**",
  "examples/**",
  "pkg/**",
  "tmp/**",
  "vendor/**"
]

test_patterns = [
  "spec/**"
]

[smells]
mode = "comment"

[[source]]
name = "default"
default = true

[[plugin]]
name = "rubocop"
mode = "monitor"
